-- Schema for the `messages` table: the text of every chat message and agent
-- reply, one row each (G17), decided on 2026-10-05 (docs/ia-proposal.md §9,
-- docs/guia-web-seguridad_modal.md §3.6). The text lives here, not in
-- `events`: replies carry balances and masked card numbers, and resuming a
-- case needs its messages by case, which `events` cannot provide. `content`
-- is application-level encrypted (AES-256-GCM, KRTR_MESSAGES_KEY), so it is
-- opaque to SQL. Rows older than 3 months are deleted by purge.sql.
-- The index on (incident_id, customer_id) was explicitly requested
-- (2026-10-05), as an exception to the CLAUDE.md no-index rule: every read
-- loads one case's messages by those two columns.
-- Consumed by krtr.back.ia.messages.store.NeonMessageStore and by
-- `krtr database neon create-schema messages`.
CREATE TABLE IF NOT EXISTS messages (
    message_id UUID PRIMARY KEY,          -- Unique ID of the message, generated by the app.
    incident_id VARCHAR(30) NOT NULL,     -- The case the message belongs to (G17).
    customer_id VARCHAR(20) NOT NULL,     -- The case's customer; every read filters by incident_id + customer_id.
    sender VARCHAR(10) NOT NULL,          -- Who wrote it: customer or agent.
    content BYTEA NOT NULL,               -- The text, AES-256-GCM encrypted (nonce + ciphertext), like events.properties. Never readable from SQL.
    language VARCHAR(5) NOT NULL,         -- es or pt-BR.
    outcome VARCHAR(30),                  -- Agent messages only: how the turn ended (resolved, needs_clarification, escalated, closed).
    sent_at TIMESTAMPTZ NOT NULL          -- When it was sent, in UTC.
);
CREATE INDEX IF NOT EXISTS messages_incident_customer_idx ON messages (incident_id, customer_id);
