-- Schema for the `events` table: the single audit-log table (G21) that
-- records every event in the krtr web app (HTTP requests, login, session
-- lifecycle, UI interactions, chat, voice, security). `properties` is
-- application-level encrypted (AES-256-GCM, see krtr/back/security/crypto/)
-- so its contents are opaque to SQL; only `event_name` and `occurred_at`
-- are queryable.
-- No indexes: the CLAUDE.md rule against creating indexes unless the user
-- explicitly asks for them applies here, and this table is purged daily
-- (see purge.sql) rather than queried at scale.
-- Consumed by krtr.back.security.audit.record_event (writes) and
-- krtr.back.security.audit's purge/sync jobs (reads/deletes).
CREATE TABLE IF NOT EXISTS events (
    id UUID PRIMARY KEY,                  -- Unique identifier of the event, generated by the app.
    event_name VARCHAR(100) NOT NULL,     -- Event type: a value of the `EventName` enum (§3.5 of the guide).
    properties BYTEA NOT NULL,            -- AES-256-GCM ciphertext (nonce + ciphertext) of the event's JSON properties. Never queryable from SQL, never holds passwords, tokens or cookies.
    occurred_at TIMESTAMPTZ NOT NULL      -- Moment the event occurred, in UTC.
);
